VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.username         = 'vagrant'
  config.ssh.private_key_path = File.expand_path('~/.ssh/azurevagrant.pem')

  # config.vm.provider = 'azure'

  do_common_azure_stuff = Proc.new do |azure, override|
      override.vm.box = 'azure'
      override.vm.box_url = 'https://github.com/msopentech/vagrant-azure/raw/master/dummy.box'
      azure.mgmt_certificate = File.expand_path('~/.ssh/azurevagrant.pem')
      azure.mgmt_endpoint    = 'https://management.core.windows.net'
      azure.subscription_id  = '5e6c7afb-c4b4-4f0f-923d-8170e88f4c4f'

      azure.vm_name     = 'azurevagrantsmall'
      #azure.vm_image    = 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2-LTS-amd64-server-20150506-en-us-30GB'
      azure.vm_image    = 'sigvisa_day95'
      azure.vm_size     = 'Basic_A3'
      azure.vm_location = 'West US'

      azure.ssh_port             = '22'
      azure.private_key_file = File.expand_path('~/.ssh/azurevagrant.pem')
      #azure.ssh_certificate_file = File.expand_path('~/.ssh/azurevagrant.cer')

      #azure.tcp_endpoints = '8000'
  end

  (1..4).each do |i|
    config.vm.define "node-#{i}" do |node|
     node.vm.provider :azure do |azure, override|
        do_common_azure_stuff.call azure, override
        azure.vm_name = "sigvisa#{i}"
        azure.cloud_service_name = "sigvisa#{i}"
     end
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
