VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.username         = 'vagrant'
  config.ssh.private_key_path = File.expand_path('~/.ssh/fabric_is_terrible.key')

  # config.vm.provider = 'azure'

  do_common_azure_stuff = Proc.new do |azure, override|
      override.vm.box = 'azure'
      override.vm.box_url = 'https://github.com/msopentech/vagrant-azure/raw/master/dummy.box'
      azure.mgmt_certificate = File.expand_path('~/.ssh/azurevagrant.pem')
      azure.mgmt_endpoint    = 'https://management.core.windows.net'
      azure.subscription_id  = '5e6c7afb-c4b4-4f0f-923d-8170e88f4c4f'

      azure.vm_name     = 'azurevagrantsmall'

      #azure.vm_image    = 'sigvisa_may16'
      #azure.vm_image     = 'run25_preloaded'
      #azure.vm_image     = 'run25_updated2'
     # azure.vm_image     = 'sigvisa_run28'

      #azure.vm_size     = 'Standard_D3_v2'
      azure.vm_size      = 'Standard_D12_v2'
      #azure.vm_size      = 'Standard_D14_v2'
      azure.vm_location = 'West US'

      azure.ssh_port             = '22'
      azure.private_key_file = File.expand_path('~/.ssh/fabric_is_terrible.key')

      azure.tcp_endpoints = '8001'
  end

  (1..1).each do |i|
    config.vm.define "nodehffix-#{i}" do |node|
     node.vm.provider :azure do |azure, override|
        do_common_azure_stuff.call azure, override
	azure.vm_image     = 'sigvisa_run28'
        azure.vm_name = "sigvisahffix#{i}"
        azure.cloud_service_name = "sigvisahffix#{i}"
     end
    end
  end

  (1..3).each do |i|
    config.vm.define "nodefix-#{i}" do |node|
     node.vm.provider :azure do |azure, override|
        do_common_azure_stuff.call azure, override
	azure.vm_image     = 'run25_updated2'
        azure.vm_name = "sigvisafix#{i}"
        azure.cloud_service_name = "sigvisafix#{i}"
     end
    end
  end


  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
