---
- name: set three-day connection timeout
  blockinfile:
    dest: /etc/mysql/my.cnf
    marker: "### {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "skip-external-locking"
    content: |
      wait_timeout=259200
      interactive_timeout=259200
- name: restart mysql to update config
  service: name=mysql state=restarted
- name: upload csv files
  become_user: sigvisa
  unarchive:
    copy=yes
    dest=/home/sigvisa/
    src=/home/dmoore/sigvisa_csv.tgz
    creates=/home/sigvisa/sigvisa_csv
- name: upload db configuration
  become_user: sigvisa
  copy:
    src=db_setup_config
    dest=/home/sigvisa/db_setup_config
- name: upload isc_origin dump
  become_user: sigvisa
  copy:
    src=isc_origin.dump
    dest=/home/sigvisa/isc_origin.dump
- name: upload llnl_wfdisc dump
  become_user: sigvisa
  copy:
    src=llnl_wfdisc.dump
    dest=/home/sigvisa/llnl_wfdisc.dump
- name: set DB password
  mysql_user: login_user=root login_password=55rontob name=root password=55rontob check_implicit_admin=yes
- name: add leb data to db
  become_user: sigvisa
  shell: /home/sigvisa/.virtualenvs/sigvisa/bin/python database/setup_db.py /home/sigvisa/db_setup_config >> /home/sigvisa/db_log 2> /home/sigvisa/db_log_errs
  environment: 
    SIGVISA_HOME: /home/sigvisa/python/sigvisa
  args:
    creates: /home/sigvisa/python/sigvisa/database/setup_db_custom.sql
    chdir: /home/sigvisa/python/sigvisa/
- name: import isc_origin table
  mysql_db: name=ctbt3mos state=import target=/home/sigvisa/isc_origin.dump login_user=root login_password=55rontob
- name: import llnl_wfdisc table
  mysql_db: name=ctbt3mos state=import target=/home/sigvisa/llnl_wfdisc.dump login_user=root login_password=55rontob